# conda environment for tiffslide development
# -------------------------------------------
#
# If you just want to install tiffslide you can do so via:
#   >>> conda install -c conda-forge tiffslide
#
name: tiffslide

channels:
  - conda-forge

dependencies:
  - python>=3.7
  - pip

  # deps
  - fsspec
  - imagecodecs
  - pillow
  - tifffile>=2020.9.22
  - zarr

  # python 3.7 compat
  - importlib_metadata
  - typing_extensions
  - cached_property

  # development dependencies
  - black
  - mypy
  - pytest>=6
  - pytest-cov
